print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")
print("hello")
print("Monty Hall Game")